# Site
repository: samsw/resume
favicon: images/favicon.ico

# Personal Info
name: Samuel T. Swanner
title: Technology Specialist Focusing on Virtualization, Cloud, AI, and Automation
email: sam@swanner.net
website: https://resume.swanner.net

# Social Links
linkedin_username: samuel-swanner-56b27313b

# About Section
about_profile_image: images/profilePic.jpg
about_content: |
  Hello! My name is Sam and welcome to my website. I am currently a Technology Specialist helping to bring in new and emerging solutions. This website currently is hosted on GitHub Pages.

# More Section
more_title: Find This Jekyll Theme

# Footer
footer_show_references: true

# Build Settings
remote_theme: samsw/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
