# Site Settings
repository: samsw/modern-resume-theme
favicon: images/favicon.ico

# Personal Info
name: Samuel T. Swanner
title: Systems Engineer Focusing on Virtualization, Cloud, Backup, and Automation
email: sam@swanner.net
website: https://resume.swanner.net

# Social Links
linkedin_username: samuel-swanner-56b27313b
github_username: samsw

# About Section
about_profile_image: images/profilePic.jpg
about_content: |
  Hello! My name is Sam and welcome to my website. I am a systems engineer that loves to learn and script. This website currently is hosted on GitHub, however at any moment it could move about!

# Footer
footer_show_references: true

# Build Settings
remote_theme: samsw/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
